using System.Text.Json;
using iTextSharp.text;
using iTextSharp.text.pdf;
using backend.Data;
using backend.Models;
using backend.Services.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace backend.Services
{
    public class PdfService : IPdfService
    {
        private readonly ApplicationDbContext _context;
        private static readonly BaseColor PrimaryColor  = new(37, 99, 235);
        private static readonly BaseColor GrayColor     = new(100, 116, 139);
        private static readonly BaseColor LightGray     = new(241, 245, 249);
        private static readonly BaseColor GreenBg       = new(220, 252, 231);
        private static readonly BaseColor AmberBg       = new(254, 243, 199);
        private static readonly BaseColor RedBg         = new(254, 226, 226);
        private static readonly BaseColor BlueBg        = new(219, 234, 254);
        private static readonly BaseColor OrangeBg      = new(255, 237, 213);

        public PdfService(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<byte[]> GenerateBusinessPlan(int ideaId)
        {
            var idea = await _context.BusinessIdeas
                .Include(i => i.User)
                .Include(i => i.Evaluation)
                .Include(i => i.FinancialPlan)
                .Include(i => i.FinancialProjection)
                    .ThenInclude(fp => fp!.Scenarios)
                .Include(i => i.FinancialProjection)
                    .ThenInclude(fp => fp!.Benchmark)
                .FirstOrDefaultAsync(i => i.IdeaId == ideaId)
                ?? throw new Exception("Idea not found");

            using var memoryStream = new MemoryStream();
            var document = new Document(PageSize.A4, 50, 50, 60, 60);
            var writer = PdfWriter.GetInstance(document, memoryStream);
            writer.PageEvent = new PageNumberEvent();

            document.Open();

            var titleFont      = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 28, PrimaryColor);
            var headingFont    = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 18, PrimaryColor);
            var subHeadingFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.DarkGray);
            var bodyFont       = FontFactory.GetFont(FontFactory.HELVETICA, 11, BaseColor.DarkGray);
            var smallFont      = FontFactory.GetFont(FontFactory.HELVETICA, 9, GrayColor);
            var boldFont       = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.DarkGray);
            var whiteBoldFont  = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.White);
            var whiteFont      = FontFactory.GetFont(FontFactory.HELVETICA, 10, BaseColor.White);

            // ── Cover Page ────────────────────────────────────────────────────────
            document.Add(new Paragraph("\n\n\n\n\n"));
            var coverTitle = new Paragraph("BUSINESS PLAN", FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 36, PrimaryColor));
            coverTitle.Alignment = Element.ALIGN_CENTER;
            document.Add(coverTitle);

            document.Add(new Paragraph("\n"));
            document.Add(new Paragraph(new Chunk(new iTextSharp.text.pdf.draw.LineSeparator(2f, 30f, PrimaryColor, Element.ALIGN_CENTER, -1))));
            document.Add(new Paragraph("\n\n"));

            var businessName = new Paragraph(idea.Title, FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 24, BaseColor.DarkGray));
            businessName.Alignment = Element.ALIGN_CENTER;
            document.Add(businessName);

            document.Add(new Paragraph("\n"));
            var sectorP = new Paragraph(idea.Sector.Replace("_", " "), FontFactory.GetFont(FontFactory.HELVETICA, 14, GrayColor));
            sectorP.Alignment = Element.ALIGN_CENTER;
            document.Add(sectorP);

            document.Add(new Paragraph("\n\n\n\n"));
            var preparedBy = new Paragraph(
                $"Prepared by: {idea.User.FullName}\nDate: {DateTime.UtcNow:MMMM dd, yyyy}\nMarket: Amman, Jordan",
                smallFont);
            preparedBy.Alignment = Element.ALIGN_CENTER;
            document.Add(preparedBy);

            document.Add(new Paragraph("\n\n\n"));
            var powered = new Paragraph("Generated by Mashroo3i — AI Business Planning Platform", FontFactory.GetFont(FontFactory.HELVETICA_OBLIQUE, 9, GrayColor));
            powered.Alignment = Element.ALIGN_CENTER;
            document.Add(powered);

            // ── Table of Contents ─────────────────────────────────────────────────
            document.NewPage();
            document.Add(new Paragraph("Table of Contents", headingFont));
            document.Add(new Paragraph("\n"));
            var tocItems = new[]
            {
                "Business Idea Summary",
                "AI Verdict",
                "Red Flags",
                "Evaluation Scores",
                "SWOT Analysis",
                "Recommendations",
                "Financial Summary",
                "12-Month Projection",
                "Benchmark Comparisons",
                "Assumptions",
                "Financial Projections (Scenario Analysis)",
            };
            for (int i = 0; i < tocItems.Length; i++)
            {
                var tocItem = new Paragraph($"{i + 1}.  {tocItems[i]}", FontFactory.GetFont(FontFactory.HELVETICA, 13, BaseColor.DarkGray));
                tocItem.SpacingAfter = 10;
                document.Add(tocItem);
            }

            // ── 1. Business Idea Summary ──────────────────────────────────────────
            document.NewPage();
            AddSectionHeader(document, "1. Business Idea Summary", headingFont);
            document.Add(new Paragraph(idea.Description, bodyFont) { SpacingAfter = 12 });

            if (!string.IsNullOrEmpty(idea.ProblemStatement))
            {
                document.Add(new Paragraph("Problem being solved", subHeadingFont) { SpacingBefore = 10, SpacingAfter = 6 });
                document.Add(new Paragraph(idea.ProblemStatement, bodyFont) { SpacingAfter = 12 });
            }
            if (!string.IsNullOrEmpty(idea.Usp))
            {
                document.Add(new Paragraph("What makes it different", subHeadingFont) { SpacingBefore = 10, SpacingAfter = 6 });
                document.Add(new Paragraph(idea.Usp, bodyFont) { SpacingAfter = 12 });
            }

            document.Add(new Paragraph("\n"));
            var infoTable = new PdfPTable(2) { WidthPercentage = 100, SpacingBefore = 6 };
            infoTable.SetWidths(new[] { 1f, 2f });
            AddTableRow(infoTable, "Sector",        idea.Sector.Replace("_", " "), boldFont, bodyFont);
            AddTableRow(infoTable, "Region",        idea.AmmanRegion + " Amman",   boldFont, bodyFont);
            AddTableRow(infoTable, "Business Type", idea.BusinessType,             boldFont, bodyFont);
            AddTableRow(infoTable, "Starting Budget", $"{idea.EstimatedBudget:N0} JOD", boldFont, bodyFont);
            if (!string.IsNullOrEmpty(idea.TargetAudience))
                AddTableRow(infoTable, "Target Audience", idea.TargetAudience, boldFont, bodyFont);
            document.Add(infoTable);

            // ── 2. AI Verdict ─────────────────────────────────────────────────────
            if (idea.Evaluation != null)
            {
                document.NewPage();
                AddSectionHeader(document, "2. AI Verdict", headingFont);

                var score    = idea.Evaluation.OverallScore;
                var riskLow  = idea.Evaluation.RiskLevel?.ToLower().Contains("low")  == true;
                var riskHigh = idea.Evaluation.RiskLevel?.ToLower().Contains("high") == true;
                BaseColor verdictBg;
                string    verdictLabel;
                if      (score >= 65 && riskLow)       { verdictBg = GreenBg; verdictLabel = "✅  This idea looks promising"; }
                else if (score < 40   || riskHigh)     { verdictBg = RedBg;   verdictLabel = "🔴  This idea carries high risk"; }
                else                                    { verdictBg = AmberBg; verdictLabel = "⚠️  This idea needs some refinement"; }

                var verdictTable = new PdfPTable(1) { WidthPercentage = 100, SpacingBefore = 8 };
                var labelCell = new PdfPCell(new Phrase(verdictLabel, boldFont))
                    { BackgroundColor = verdictBg, Padding = 12, BorderColor = BaseColor.White };
                verdictTable.AddCell(labelCell);
                if (!string.IsNullOrEmpty(idea.Evaluation.Verdict))
                {
                    var textCell = new PdfPCell(new Phrase(idea.Evaluation.Verdict, bodyFont))
                        { BackgroundColor = verdictBg, Padding = 12, PaddingTop = 4, BorderColor = BaseColor.White };
                    verdictTable.AddCell(textCell);
                }
                document.Add(verdictTable);
            }

            // ── 3. Red Flags ──────────────────────────────────────────────────────
            if (idea.Evaluation != null && !string.IsNullOrEmpty(idea.Evaluation.RedFlags))
            {
                var evalRedFlags = ParseStringArray(idea.Evaluation.RedFlags);
                // Also pull financial red flags from FinancialSummary
                var finRedFlags  = idea.FinancialPlan != null
                    ? ParseFinancialArray(idea.FinancialPlan.FinancialSummary, "redFlags")
                    : new List<string>();
                var allRedFlags  = evalRedFlags.Concat(finRedFlags).Distinct().ToList();

                if (allRedFlags.Count > 0)
                {
                    document.Add(new Paragraph("\n"));
                    AddSectionHeader(document, "3. Red Flags", headingFont);

                    var rfTable = new PdfPTable(1) { WidthPercentage = 100, SpacingBefore = 8 };
                    var list = new List(List.UNORDERED);
                    list.SetListSymbol("⚠  ");
                    foreach (var flag in allRedFlags)
                        list.Add(new ListItem(flag, bodyFont));
                    var rfCell = new PdfPCell { BackgroundColor = AmberBg, Padding = 12, BorderColor = BaseColor.White };
                    rfCell.AddElement(list);
                    rfTable.AddCell(rfCell);
                    document.Add(rfTable);
                }
            }

            // ── 4. Evaluation Scores ──────────────────────────────────────────────
            if (idea.Evaluation != null)
            {
                document.NewPage();
                AddSectionHeader(document, "4. Evaluation Scores", headingFont);

                var headerBg   = new BaseColor(238, 242, 255);
                var evalTable  = new PdfPTable(4) { WidthPercentage = 100, SpacingBefore = 10 };
                foreach (var h in new[] { "How Original", "Market Opportunity", "Overall Score", "Risk Assessment" })
                {
                    evalTable.AddCell(new PdfPCell(new Phrase(h, boldFont))
                        { BackgroundColor = headerBg, Padding = 10, HorizontalAlignment = Element.ALIGN_CENTER });
                }
                foreach (var v in new[] {
                    idea.Evaluation.NoveltyScore.ToString(),
                    idea.Evaluation.MarketPotentialScore.ToString(),
                    idea.Evaluation.OverallScore.ToString(),
                    idea.Evaluation.RiskLevel })
                {
                    evalTable.AddCell(new PdfPCell(new Phrase(v, bodyFont))
                        { Padding = 10, HorizontalAlignment = Element.ALIGN_CENTER });
                }
                document.Add(evalTable);
            }

            // ── 5. SWOT Analysis ──────────────────────────────────────────────────
            if (idea.Evaluation != null)
            {
                document.NewPage();
                AddSectionHeader(document, "5. SWOT Analysis", headingFont);

                try
                {
                    var swotJson = JsonDocument.Parse(idea.Evaluation.SwotAnalysis);
                    var root = swotJson.RootElement;
                    AddSwotSection(document, "Strengths",     root, "Strengths",     GreenBg,  subHeadingFont, bodyFont);
                    AddSwotSection(document, "Weaknesses",    root, "Weaknesses",    RedBg,    subHeadingFont, bodyFont);
                    AddSwotSection(document, "Opportunities", root, "Opportunities", BlueBg,   subHeadingFont, bodyFont);
                    AddSwotSection(document, "Threats",       root, "Threats",       OrangeBg, subHeadingFont, bodyFont);
                }
                catch { }
            }

            // ── 6. Recommendations ────────────────────────────────────────────────
            if (!string.IsNullOrEmpty(idea.Evaluation?.Recommendations))
            {
                document.NewPage();
                AddSectionHeader(document, "6. What to do next", headingFont);

                var recLines = idea.Evaluation.Recommendations
                    .Split('\n', StringSplitOptions.RemoveEmptyEntries)
                    .Where(l => l.Trim().Length > 0)
                    .ToArray();

                var numberedList = new List(List.ORDERED);
                foreach (var rec in recLines)
                    numberedList.Add(new ListItem(rec.Trim(), bodyFont));
                document.Add(numberedList);
            }

            // ── 7. Financial Summary ──────────────────────────────────────────────
            if (idea.FinancialPlan != null)
            {
                document.NewPage();
                AddSectionHeader(document, "7. Financial Summary", headingFont);

                // Top-line figures
                var finTopTable = new PdfPTable(2) { WidthPercentage = 100, SpacingBefore = 10 };
                finTopTable.SetWidths(new[] { 1f, 1f });
                AddTableRow(finTopTable, "Starting budget",    $"{idea.FinancialPlan.InitialInvestment:N0} JOD", boldFont, bodyFont);
                AddTableRow(finTopTable, "Monthly income",     $"{idea.FinancialPlan.MonthlyRevenue:N0} JOD",   boldFont, bodyFont);
                AddTableRow(finTopTable, "Monthly expenses",   $"{idea.FinancialPlan.MonthlyCosts:N0} JOD",     boldFont, bodyFont);
                AddTableRow(finTopTable, "Monthly profit",     $"{(idea.FinancialPlan.MonthlyRevenue - idea.FinancialPlan.MonthlyCosts):N0} JOD", boldFont, bodyFont);
                AddTableRow(finTopTable, "Time to break even", idea.FinancialPlan.BreakEvenMonths > 0 ? $"{idea.FinancialPlan.BreakEvenMonths} months" : "N/A", boldFont, bodyFont);
                AddTableRow(finTopTable, "2-year return on investment (ROI)", $"{idea.FinancialPlan.RoiPercentage:F1}%", boldFont, bodyFont);
                document.Add(finTopTable);

                // 3 Scenario cards
                var conservative = GetScenario(idea.FinancialPlan.FinancialSummary, "conservative");
                var realistic    = GetScenario(idea.FinancialPlan.FinancialSummary, "realistic");
                var optimistic   = GetScenario(idea.FinancialPlan.FinancialSummary, "optimistic");

                if (conservative != null || realistic != null || optimistic != null)
                {
                    document.Add(new Paragraph("\nScenario Comparison", subHeadingFont) { SpacingBefore = 16, SpacingAfter = 8 });
                    var scenTable = new PdfPTable(3) { WidthPercentage = 100 };

                    foreach (var (label, scenario, bg) in new[] {
                        ("Conservative", conservative, LightGray),
                        ("Realistic",    realistic,    new BaseColor(238, 242, 255)),
                        ("Optimistic",   optimistic,   new BaseColor(240, 253, 244)),
                    })
                    {
                        var cell = new PdfPCell { BackgroundColor = bg, Padding = 10, BorderColor = BaseColor.White };
                        cell.AddElement(new Paragraph(label, boldFont) { SpacingAfter = 6 });
                        if (scenario != null)
                        {
                            cell.AddElement(new Paragraph($"Income:   {scenario.revenue:N0} JOD", bodyFont));
                            cell.AddElement(new Paragraph($"Expenses: {scenario.costs:N0} JOD",   bodyFont));
                            cell.AddElement(new Paragraph($"Profit:   {scenario.profit:N0} JOD",  bodyFont));
                            cell.AddElement(new Paragraph($"Break-even: {(scenario.bep > 0 && scenario.bep < 9999 ? scenario.bep + " mo" : "N/A")}", bodyFont));
                        }
                        else
                        {
                            cell.AddElement(new Paragraph("N/A", bodyFont));
                        }
                        scenTable.AddCell(cell);
                    }
                    document.Add(scenTable);
                }
            }

            // ── 8. 12-Month Projection ────────────────────────────────────────────
            if (idea.FinancialPlan != null)
            {
                var projections = GetProjections(idea.FinancialPlan.FinancialSummary);
                if (projections.Count > 0)
                {
                    document.NewPage();
                    AddSectionHeader(document, "8. 12-Month Projection", headingFont);

                    var projTable = new PdfPTable(4) { WidthPercentage = 100, SpacingBefore = 10 };
                    var projHeaderBg = new BaseColor(238, 242, 255);
                    foreach (var h in new[] { "Month", "Monthly income", "Monthly expenses", "Monthly profit" })
                    {
                        projTable.AddCell(new PdfPCell(new Phrase(h, boldFont))
                            { BackgroundColor = projHeaderBg, Padding = 8, HorizontalAlignment = Element.ALIGN_CENTER });
                    }
                    foreach (var p in projections.Take(12))
                    {
                        var profit = p.revenue - p.costs;
                        var profitColor = profit >= 0 ? new BaseColor(22, 163, 74) : new BaseColor(220, 38, 38);
                        projTable.AddCell(new PdfPCell(new Phrase($"M{p.month}", bodyFont))
                            { Padding = 7, HorizontalAlignment = Element.ALIGN_CENTER });
                        projTable.AddCell(new PdfPCell(new Phrase($"{p.revenue:N0}", bodyFont))
                            { Padding = 7, HorizontalAlignment = Element.ALIGN_RIGHT });
                        projTable.AddCell(new PdfPCell(new Phrase($"{p.costs:N0}", bodyFont))
                            { Padding = 7, HorizontalAlignment = Element.ALIGN_RIGHT });
                        projTable.AddCell(new PdfPCell(new Phrase($"{profit:N0}", FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 10, profitColor)))
                            { Padding = 7, HorizontalAlignment = Element.ALIGN_RIGHT });
                    }
                    document.Add(projTable);
                    document.Add(new Paragraph("All figures in JOD.", smallFont) { SpacingBefore = 6 });
                }
            }

            // ── 9. Benchmark Comparisons ──────────────────────────────────────────
            if (idea.FinancialPlan != null)
            {
                var benchmarks = GetBenchmarks(idea.FinancialPlan.FinancialSummary);
                if (benchmarks.Count > 0)
                {
                    document.NewPage();
                    AddSectionHeader(document, "9. How You Compare to Similar Amman Businesses", headingFont);

                    var bmTable = new PdfPTable(4) { WidthPercentage = 100, SpacingBefore = 10 };
                    bmTable.SetWidths(new[] { 2f, 1.5f, 1.5f, 0.8f });
                    var bmHeaderBg = new BaseColor(238, 242, 255);
                    foreach (var h in new[] { "What", "Your Value", "Amman Benchmark", "Status" })
                    {
                        bmTable.AddCell(new PdfPCell(new Phrase(h, boldFont))
                            { BackgroundColor = bmHeaderBg, Padding = 8 });
                    }
                    foreach (var b in benchmarks)
                    {
                        bmTable.AddCell(new PdfPCell(new Phrase(b.metric,    bodyFont)) { Padding = 7 });
                        bmTable.AddCell(new PdfPCell(new Phrase(b.yourValue, bodyFont)) { Padding = 7 });
                        bmTable.AddCell(new PdfPCell(new Phrase(b.benchmark, bodyFont)) { Padding = 7 });
                        var statusText = b.status == "ok" ? "✅" : b.status == "warning" ? "⚠️" : "🔴";
                        bmTable.AddCell(new PdfPCell(new Phrase(statusText, bodyFont))
                            { Padding = 7, HorizontalAlignment = Element.ALIGN_CENTER });
                    }
                    document.Add(bmTable);
                }
            }

            // ── 10. Assumptions ───────────────────────────────────────────────────
            if (idea.FinancialPlan != null)
            {
                var assumptions = ParseFinancialArray(idea.FinancialPlan.FinancialSummary, "assumptionsLog");
                if (assumptions.Count > 0)
                {
                    document.Add(new Paragraph("\n"));
                    AddSectionHeader(document, "10. What We Assumed in This Calculation", headingFont);

                    var assumList = new List(List.UNORDERED);
                    assumList.SetListSymbol("\u2022  ");
                    foreach (var item in assumptions)
                        assumList.Add(new ListItem(item, bodyFont));
                    document.Add(assumList);
                }
            }

            // ── 11. Financial Projections (Scenario Analysis) ────────────────────
            if (idea.FinancialProjection != null)
            {
                var fp = idea.FinancialProjection;
                document.NewPage();
                AddSectionHeader(document, "11. Financial Projections (Scenario Analysis)", headingFont);

                // Industry + business model info
                var fpInfoTable = new PdfPTable(2) { WidthPercentage = 100, SpacingBefore = 6 };
                fpInfoTable.SetWidths(new[] { 1f, 2f });
                AddTableRow(fpInfoTable, "Industry",       fp.Benchmark?.IndustryNameEn ?? fp.SelectedIndustryType, boldFont, bodyFont);
                AddTableRow(fpInfoTable, "Business Model", fp.SelectedBusinessModel,                               boldFont, bodyFont);
                if (fp.Benchmark != null)
                {
                    AddTableRow(fpInfoTable, "Data Confidence", $"{fp.Benchmark.ConfidenceLevel} ({fp.Benchmark.Confidence * 100:F0}%)", boldFont, bodyFont);
                    AddTableRow(fpInfoTable, "Region",          fp.Benchmark.Region,                                                       boldFont, bodyFont);
                }
                document.Add(fpInfoTable);

                // Data sources
                if (fp.Benchmark?.DataSourcesJson is not null)
                {
                    try
                    {
                        var sources = JsonSerializer.Deserialize<List<string>>(fp.Benchmark.DataSourcesJson) ?? new();
                        if (sources.Count > 0)
                        {
                            document.Add(new Paragraph("Data Sources", subHeadingFont) { SpacingBefore = 14, SpacingAfter = 4 });
                            var srcList = new List(List.UNORDERED);
                            srcList.SetListSymbol("\u2022  ");
                            foreach (var src in sources)
                                srcList.Add(new ListItem(src, smallFont));
                            document.Add(srcList);
                        }
                    }
                    catch { }
                }

                // 3-Scenario side-by-side table
                var optimistic   = fp.Scenarios.FirstOrDefault(s => s.ScenarioName == "Optimistic");
                var realistic    = fp.Scenarios.FirstOrDefault(s => s.ScenarioName == "Realistic");
                var pessimistic  = fp.Scenarios.FirstOrDefault(s => s.ScenarioName == "Pessimistic");

                if (optimistic != null || realistic != null || pessimistic != null)
                {
                    document.Add(new Paragraph("Scenario Comparison (12 Months)", subHeadingFont) { SpacingBefore = 16, SpacingAfter = 8 });

                    // Header row
                    var scn3Table = new PdfPTable(4) { WidthPercentage = 100, SpacingBefore = 6 };
                    scn3Table.SetWidths(new[] { 2f, 1.5f, 1.5f, 1.5f });
                    var scnHeaderBg = new BaseColor(238, 242, 255);
                    foreach (var h in new[] { "Metric", "Optimistic", "Realistic", "Pessimistic" })
                    {
                        scn3Table.AddCell(new PdfPCell(new Phrase(h, boldFont))
                            { BackgroundColor = scnHeaderBg, Padding = 9, HorizontalAlignment = Element.ALIGN_CENTER });
                    }

                    static string BepLabel(int m) => m <= 0 ? "N/A" : m > 12 ? "> 12 mo" : $"{m} mo";
                    static string RoiLabel(decimal r) => $"{r:F1}%";
                    static string ProfitLabel(decimal p) => $"{Math.Round(p):N0} JOD";

                    // Break-even row
                    var bepBg = new BaseColor(240, 253, 244);
                    scn3Table.AddCell(new PdfPCell(new Phrase("Break-even Month", boldFont)) { Padding = 8, BackgroundColor = LightGray, BorderColor = BaseColor.White });
                    foreach (var s in new[] { optimistic, realistic, pessimistic })
                    {
                        scn3Table.AddCell(new PdfPCell(new Phrase(s != null ? BepLabel(s.BreakEvenMonth) : "—", bodyFont))
                            { Padding = 8, HorizontalAlignment = Element.ALIGN_CENTER });
                    }

                    // ROI row
                    scn3Table.AddCell(new PdfPCell(new Phrase("12-Month ROI", boldFont)) { Padding = 8, BackgroundColor = LightGray, BorderColor = BaseColor.White });
                    foreach (var s in new[] { optimistic, realistic, pessimistic })
                    {
                        scn3Table.AddCell(new PdfPCell(new Phrase(s != null ? RoiLabel(s.ROI12Months) : "—", bodyFont))
                            { Padding = 8, HorizontalAlignment = Element.ALIGN_CENTER });
                    }

                    // Total profit row
                    scn3Table.AddCell(new PdfPCell(new Phrase("Total 12-Month Profit", boldFont)) { Padding = 8, BackgroundColor = LightGray, BorderColor = BaseColor.White });
                    foreach (var s in new[] { optimistic, realistic, pessimistic })
                    {
                        var profit = s?.TotalProfit12Months ?? 0;
                        var profitFont = profit >= 0
                            ? FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 10, new BaseColor(22, 163, 74))
                            : FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 10, new BaseColor(220, 38, 38));
                        scn3Table.AddCell(new PdfPCell(new Phrase(s != null ? ProfitLabel(profit) : "—", profitFont))
                            { Padding = 8, HorizontalAlignment = Element.ALIGN_CENTER });
                    }

                    // Cumulative cash flow row
                    scn3Table.AddCell(new PdfPCell(new Phrase("Cumulative Cash Flow", boldFont)) { Padding = 8, BackgroundColor = LightGray, BorderColor = BaseColor.White });
                    foreach (var s in new[] { optimistic, realistic, pessimistic })
                    {
                        var cf = s?.CumulativeCashFlow12Months ?? 0;
                        var cfFont = cf >= 0
                            ? FontFactory.GetFont(FontFactory.HELVETICA, 10, new BaseColor(22, 163, 74))
                            : FontFactory.GetFont(FontFactory.HELVETICA, 10, new BaseColor(220, 38, 38));
                        scn3Table.AddCell(new PdfPCell(new Phrase(s != null ? ProfitLabel(cf) : "—", cfFont))
                            { Padding = 8, HorizontalAlignment = Element.ALIGN_CENTER });
                    }

                    document.Add(scn3Table);
                }

                // Monthly data table — Realistic scenario only
                if (realistic != null && !string.IsNullOrEmpty(realistic.MonthlyDataJson))
                {
                    try
                    {
                        var monthlyRows = JsonSerializer.Deserialize<List<MonthlyProjectionData>>(
                            realistic.MonthlyDataJson,
                            new JsonSerializerOptions { PropertyNameCaseInsensitive = true }) ?? new();

                        if (monthlyRows.Count > 0)
                        {
                            document.Add(new Paragraph("Monthly Breakdown — Realistic Scenario", subHeadingFont) { SpacingBefore = 18, SpacingAfter = 8 });

                            var mTable = new PdfPTable(6) { WidthPercentage = 100, SpacingBefore = 6 };
                            mTable.SetWidths(new[] { 0.6f, 1.3f, 1.3f, 1.3f, 0.9f, 1.5f });
                            var mHeaderBg = new BaseColor(238, 242, 255);
                            foreach (var h in new[] { "Mo.", "Revenue", "Costs", "Profit", "Margin", "Cum. Cash Flow" })
                            {
                                mTable.AddCell(new PdfPCell(new Phrase(h, boldFont))
                                    { BackgroundColor = mHeaderBg, Padding = 7, HorizontalAlignment = Element.ALIGN_CENTER });
                            }

                            foreach (var row in monthlyRows.Take(12))
                            {
                                var profitColor = row.Profit >= 0
                                    ? new BaseColor(22, 163, 74)
                                    : new BaseColor(220, 38, 38);
                                var profitRowFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 9, profitColor);

                                mTable.AddCell(new PdfPCell(new Phrase($"M{row.Month}", smallFont))
                                    { Padding = 6, HorizontalAlignment = Element.ALIGN_CENTER });
                                mTable.AddCell(new PdfPCell(new Phrase($"{Math.Round(row.Revenue):N0}", bodyFont))
                                    { Padding = 6, HorizontalAlignment = Element.ALIGN_RIGHT });
                                mTable.AddCell(new PdfPCell(new Phrase($"{Math.Round(row.Costs):N0}", bodyFont))
                                    { Padding = 6, HorizontalAlignment = Element.ALIGN_RIGHT });
                                mTable.AddCell(new PdfPCell(new Phrase($"{Math.Round(row.Profit):N0}", profitRowFont))
                                    { Padding = 6, HorizontalAlignment = Element.ALIGN_RIGHT });
                                mTable.AddCell(new PdfPCell(new Phrase($"{row.MarginPercent:F1}%", bodyFont))
                                    { Padding = 6, HorizontalAlignment = Element.ALIGN_CENTER });
                                mTable.AddCell(new PdfPCell(new Phrase($"{Math.Round(row.CumulativeCashFlow):N0}", bodyFont))
                                    { Padding = 6, HorizontalAlignment = Element.ALIGN_RIGHT });
                            }
                            document.Add(mTable);
                            document.Add(new Paragraph("All figures in JOD.", smallFont) { SpacingBefore = 5 });
                        }
                    }
                    catch { }
                }

                // Arabic disclaimer note
                document.Add(new Paragraph("\n"));
                var fpDisclTable = new PdfPTable(1) { WidthPercentage = 100 };
                fpDisclTable.AddCell(new PdfPCell(new Phrase(
                    "هذه التوقعات مبنية على بيانات مرجعية من مشاريع مماثلة في عمّان ولا تُعدّ ضماناً للنتائج الفعلية.",
                    smallFont))
                {
                    BackgroundColor = new BaseColor(238, 242, 255), Padding = 10, BorderColor = BaseColor.White
                });
                document.Add(fpDisclTable);
            }

            // ── 12. Disclaimer ────────────────────────────────────────────────────
            document.Add(new Paragraph("\n\n"));
            var disclaimerTable = new PdfPTable(1) { WidthPercentage = 100 };
            var disclaimerCell = new PdfPCell(new Phrase(
                "📍 All benchmarks and evaluations are based on research into Amman's market (2025). " +
                "Results may vary for other cities or unusual business models. " +
                "This document is for planning purposes only and does not constitute financial or legal advice.",
                smallFont))
            {
                BackgroundColor = LightGray, Padding = 12, BorderColor = BaseColor.White
            };
            disclaimerTable.AddCell(disclaimerCell);
            document.Add(disclaimerTable);

            document.Close();
            return memoryStream.ToArray();
        }

        // ── Helpers ───────────────────────────────────────────────────────────────

        private void AddSectionHeader(Document doc, string title, Font font)
        {
            doc.Add(new Paragraph(title, font) { SpacingAfter = 15 });
            doc.Add(new Paragraph(new Chunk(new iTextSharp.text.pdf.draw.LineSeparator(1f, 100f, LightGray, Element.ALIGN_LEFT, -1))));
            doc.Add(new Paragraph("\n"));
        }

        private void AddTableRow(PdfPTable table, string label, string value, Font labelFont, Font valueFont)
        {
            table.AddCell(new PdfPCell(new Phrase(label, labelFont))
                { Padding = 8, BackgroundColor = LightGray, BorderColor = BaseColor.White });
            table.AddCell(new PdfPCell(new Phrase(value, valueFont))
                { Padding = 8, BorderColor = BaseColor.White });
        }

        private void AddSwotSection(Document doc, string title, JsonElement root, string key, BaseColor bgColor, Font headFont, Font bodyFont)
        {
            if (root.TryGetProperty(key, out var items) && items.ValueKind == JsonValueKind.Array)
            {
                var cell = new PdfPTable(1) { WidthPercentage = 100, SpacingBefore = 8 };
                cell.AddCell(new PdfPCell(new Phrase(title, headFont))
                    { BackgroundColor = bgColor, Padding = 10, BorderColor = BaseColor.White });

                var list = new List(List.UNORDERED);
                list.SetListSymbol("\u2022  ");
                foreach (var item in items.EnumerateArray())
                    list.Add(new ListItem(item.GetString() ?? "", bodyFont));

                var contentCell = new PdfPCell { Padding = 10, BorderColor = BaseColor.White };
                contentCell.AddElement(list);
                cell.AddCell(contentCell);
                doc.Add(cell);
            }
        }

        private static List<string> ParseStringArray(string? json)
        {
            if (string.IsNullOrEmpty(json)) return new();
            try
            {
                if (json.TrimStart().StartsWith('['))
                    return JsonSerializer.Deserialize<List<string>>(json) ?? new();
                return new List<string> { json };
            }
            catch { return new(); }
        }

        private static List<string> ParseFinancialArray(string? summaryJson, string arrayKey)
        {
            if (string.IsNullOrEmpty(summaryJson)) return new();
            try
            {
                var doc  = JsonDocument.Parse(summaryJson).RootElement;
                if (doc.TryGetProperty(arrayKey, out var arr) && arr.ValueKind == JsonValueKind.Array)
                    return arr.EnumerateArray().Select(e => e.GetString() ?? "").Where(s => s.Length > 0).ToList();
            }
            catch { }
            return new();
        }

        private record ScenarioValues(decimal revenue, decimal costs, decimal profit, int bep);

        private static ScenarioValues? GetScenario(string? summaryJson, string key)
        {
            if (string.IsNullOrEmpty(summaryJson)) return null;
            try
            {
                var root = JsonDocument.Parse(summaryJson).RootElement;
                if (!root.TryGetProperty(key, out var s)) return null;
                return new ScenarioValues(
                    GetDecimal(s, "monthlyRevenue"),
                    GetDecimal(s, "monthlyCosts"),
                    GetDecimal(s, "monthlyProfit"),
                    GetInt(s, "breakEvenMonths"));
            }
            catch { return null; }
        }

        private record ProjectionRow(int month, decimal revenue, decimal costs);

        private static List<ProjectionRow> GetProjections(string? summaryJson)
        {
            if (string.IsNullOrEmpty(summaryJson)) return new();
            try
            {
                var root = JsonDocument.Parse(summaryJson).RootElement;
                if (!root.TryGetProperty("monthlyProjections", out var arr) || arr.ValueKind != JsonValueKind.Array)
                    return new();
                return arr.EnumerateArray().Select(p => new ProjectionRow(
                    GetInt(p, "month"),
                    GetDecimal(p, "revenue"),
                    GetDecimal(p, "costs")
                )).ToList();
            }
            catch { return new(); }
        }

        private record BenchmarkRow(string metric, string yourValue, string benchmark, string status);

        private static List<BenchmarkRow> GetBenchmarks(string? summaryJson)
        {
            if (string.IsNullOrEmpty(summaryJson)) return new();
            try
            {
                var root = JsonDocument.Parse(summaryJson).RootElement;
                if (!root.TryGetProperty("benchmarkComparisons", out var arr) || arr.ValueKind != JsonValueKind.Array)
                    return new();
                return arr.EnumerateArray().Select(b => new BenchmarkRow(
                    GetString(b, "metric"),
                    GetString(b, "yourValue"),
                    GetString(b, "benchmarkTypical"),
                    GetString(b, "status")
                )).ToList();
            }
            catch { return new(); }
        }

        private static decimal GetDecimal(JsonElement el, string key) =>
            el.TryGetProperty(key, out var v) && v.TryGetDecimal(out var d) ? d : 0m;

        private static int GetInt(JsonElement el, string key) =>
            el.TryGetProperty(key, out var v) && v.TryGetInt32(out var i) ? i : 0;

        private static string GetString(JsonElement el, string key) =>
            el.TryGetProperty(key, out var v) ? v.GetString() ?? "" : "";

        private class PageNumberEvent : PdfPageEventHelper
        {
            public override void OnEndPage(PdfWriter writer, Document document)
            {
                var font  = FontFactory.GetFont(FontFactory.HELVETICA, 8, new BaseColor(148, 163, 184));
                var table = new PdfPTable(1) { TotalWidth = document.PageSize.Width - 100 };
                table.AddCell(new PdfPCell(new Phrase($"Page {writer.PageNumber} | Mashroo3i Business Plan", font))
                    { Border = Rectangle.NO_BORDER, HorizontalAlignment = Element.ALIGN_CENTER });
                table.WriteSelectedRows(0, -1, 50, 40, writer.DirectContent);
            }
        }
    }
}
