using System.Text.Json;
using iTextSharp.text;
using iTextSharp.text.pdf;
using backend.Data;
using backend.Services.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace backend.Services
{
    public class PdfService : IPdfService
    {
        private readonly ApplicationDbContext _context;
        private static readonly BaseColor PrimaryColor = new(37, 99, 235);
        private static readonly BaseColor GrayColor = new(100, 116, 139);
        private static readonly BaseColor LightGray = new(241, 245, 249);

        public PdfService(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<byte[]> GenerateBusinessPlan(int ideaId)
        {
            var idea = await _context.BusinessIdeas
                .Include(i => i.User)
                .Include(i => i.Evaluation)
                .Include(i => i.FinancialPlan)
                .FirstOrDefaultAsync(i => i.IdeaId == ideaId)
                ?? throw new Exception("Idea not found");

            using var memoryStream = new MemoryStream();
            var document = new Document(PageSize.A4, 50, 50, 60, 60);
            var writer = PdfWriter.GetInstance(document, memoryStream);
            writer.PageEvent = new PageNumberEvent();

            document.Open();

            var titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 28, PrimaryColor);
            var headingFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 18, PrimaryColor);
            var subHeadingFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 14, BaseColor.DarkGray);
            var bodyFont = FontFactory.GetFont(FontFactory.HELVETICA, 11, BaseColor.DarkGray);
            var smallFont = FontFactory.GetFont(FontFactory.HELVETICA, 9, GrayColor);
            var boldFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 11, BaseColor.DarkGray);

            // ---- Cover Page ----
            document.Add(new Paragraph("\n\n\n\n\n"));
            var coverTitle = new Paragraph("BUSINESS PLAN", FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 36, PrimaryColor));
            coverTitle.Alignment = Element.ALIGN_CENTER;
            document.Add(coverTitle);

            document.Add(new Paragraph("\n"));
            var line = new Paragraph(new Chunk(new iTextSharp.text.pdf.draw.LineSeparator(2f, 30f, PrimaryColor, Element.ALIGN_CENTER, -1)));
            document.Add(line);
            document.Add(new Paragraph("\n\n"));

            var businessName = new Paragraph(idea.Title, FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 24, BaseColor.DarkGray));
            businessName.Alignment = Element.ALIGN_CENTER;
            document.Add(businessName);

            document.Add(new Paragraph("\n"));
            var sectorP = new Paragraph(idea.Sector, FontFactory.GetFont(FontFactory.HELVETICA, 14, GrayColor));
            sectorP.Alignment = Element.ALIGN_CENTER;
            document.Add(sectorP);

            document.Add(new Paragraph("\n\n\n\n"));
            var preparedBy = new Paragraph($"Prepared by: {idea.User.FullName}\nDate: {DateTime.UtcNow:MMMM dd, yyyy}\nLocation: Amman, Jordan", smallFont);
            preparedBy.Alignment = Element.ALIGN_CENTER;
            document.Add(preparedBy);

            document.Add(new Paragraph("\n\n\n"));
            var powered = new Paragraph("Generated by Mashroo3i - AI Business Planning Platform", FontFactory.GetFont(FontFactory.HELVETICA_OBLIQUE, 9, GrayColor));
            powered.Alignment = Element.ALIGN_CENTER;
            document.Add(powered);

            // ---- Table of Contents ----
            document.NewPage();
            document.Add(new Paragraph("Table of Contents", headingFont));
            document.Add(new Paragraph("\n"));
            var tocItems = new[] { "Executive Summary", "Business Description", "AI Evaluation Results", "SWOT Analysis", "Market Analysis", "Financial Projections", "Recommendations" };
            for (int i = 0; i < tocItems.Length; i++)
            {
                var tocItem = new Paragraph($"{i + 1}.  {tocItems[i]}", FontFactory.GetFont(FontFactory.HELVETICA, 13, BaseColor.DarkGray));
                tocItem.SpacingAfter = 10;
                document.Add(tocItem);
            }

            // ---- 1. Executive Summary ----
            document.NewPage();
            AddSectionHeader(document, "1. Executive Summary", headingFont);
            document.Add(new Paragraph(idea.Description, bodyFont) { SpacingAfter = 12 });

            if (!string.IsNullOrEmpty(idea.ProblemStatement))
            {
                document.Add(new Paragraph("Problem Statement", subHeadingFont) { SpacingBefore = 10, SpacingAfter = 6 });
                document.Add(new Paragraph(idea.ProblemStatement, bodyFont) { SpacingAfter = 12 });
            }

            if (!string.IsNullOrEmpty(idea.Usp))
            {
                document.Add(new Paragraph("Unique Selling Point", subHeadingFont) { SpacingBefore = 10, SpacingAfter = 6 });
                document.Add(new Paragraph(idea.Usp, bodyFont) { SpacingAfter = 12 });
            }

            // ---- 2. Business Description ----
            document.NewPage();
            AddSectionHeader(document, "2. Business Description", headingFont);

            var descTable = new PdfPTable(2) { WidthPercentage = 100, SpacingBefore = 10 };
            descTable.SetWidths(new[] { 1f, 2f });
            AddTableRow(descTable, "Sector", idea.Sector, boldFont, bodyFont);
            AddTableRow(descTable, "Region", idea.AmmanRegion + " Amman", boldFont, bodyFont);
            AddTableRow(descTable, "Business Type", idea.BusinessType, boldFont, bodyFont);
            AddTableRow(descTable, "Budget", $"{idea.EstimatedBudget:N0} JOD", boldFont, bodyFont);
            AddTableRow(descTable, "Competition", idea.CompetitionLevel ?? "N/A", boldFont, bodyFont);
            AddTableRow(descTable, "Target Audience", idea.TargetAudience ?? "N/A", boldFont, bodyFont);
            AddTableRow(descTable, "Market Size", idea.MarketSize ?? "N/A", boldFont, bodyFont);
            document.Add(descTable);

            if (idea.User != null)
            {
                document.Add(new Paragraph("\nFounder Profile", subHeadingFont) { SpacingAfter = 6 });
                var founderTable = new PdfPTable(2) { WidthPercentage = 100 };
                founderTable.SetWidths(new[] { 1f, 2f });
                AddTableRow(founderTable, "Name", idea.User.FullName, boldFont, bodyFont);
                AddTableRow(founderTable, "Education", idea.User.Education ?? "N/A", boldFont, bodyFont);
                AddTableRow(founderTable, "Experience", idea.User.Experience ?? "N/A", boldFont, bodyFont);
                document.Add(founderTable);
            }

            // ---- 3. AI Evaluation ----
            if (idea.Evaluation != null)
            {
                document.NewPage();
                AddSectionHeader(document, "3. AI Evaluation Results", headingFont);

                var evalTable = new PdfPTable(4) { WidthPercentage = 100, SpacingBefore = 10 };
                var headerBg = new BaseColor(238, 242, 255);

                foreach (var h in new[] { "Novelty Score", "Market Potential", "Overall Score", "Risk Level" })
                {
                    var cell = new PdfPCell(new Phrase(h, boldFont)) { BackgroundColor = headerBg, Padding = 10, HorizontalAlignment = Element.ALIGN_CENTER };
                    evalTable.AddCell(cell);
                }
                foreach (var v in new[] { idea.Evaluation.NoveltyScore.ToString(), idea.Evaluation.MarketPotentialScore.ToString(), idea.Evaluation.OverallScore.ToString(), idea.Evaluation.RiskLevel })
                {
                    var cell = new PdfPCell(new Phrase(v, bodyFont)) { Padding = 10, HorizontalAlignment = Element.ALIGN_CENTER };
                    evalTable.AddCell(cell);
                }
                document.Add(evalTable);
            }

            // ---- 4. SWOT Analysis ----
            if (idea.Evaluation != null)
            {
                document.NewPage();
                AddSectionHeader(document, "4. SWOT Analysis", headingFont);

                try
                {
                    var swotJson = JsonDocument.Parse(idea.Evaluation.SwotAnalysis);
                    var root = swotJson.RootElement;
                    AddSwotSection(document, "Strengths", root, "Strengths", new BaseColor(220, 252, 231), subHeadingFont, bodyFont);
                    AddSwotSection(document, "Weaknesses", root, "Weaknesses", new BaseColor(254, 226, 226), subHeadingFont, bodyFont);
                    AddSwotSection(document, "Opportunities", root, "Opportunities", new BaseColor(219, 234, 254), subHeadingFont, bodyFont);
                    AddSwotSection(document, "Threats", root, "Threats", new BaseColor(255, 237, 213), subHeadingFont, bodyFont);
                }
                catch { }

                if (!string.IsNullOrEmpty(idea.Evaluation.Recommendations))
                {
                    document.Add(new Paragraph("\n"));
                    AddSectionHeader(document, "7. Recommendations", headingFont);
                    document.Add(new Paragraph(idea.Evaluation.Recommendations, bodyFont) { SpacingAfter = 12 });
                }
            }

            // ---- 5. Market Analysis ----
            document.NewPage();
            AddSectionHeader(document, "5. Market Analysis", headingFont);
            document.Add(new Paragraph("Target Market", subHeadingFont) { SpacingAfter = 6 });
            document.Add(new Paragraph(idea.TargetAudience ?? "Not specified", bodyFont) { SpacingAfter = 12 });
            document.Add(new Paragraph("Market Size", subHeadingFont) { SpacingAfter = 6 });
            document.Add(new Paragraph(idea.MarketSize ?? "Not specified", bodyFont) { SpacingAfter = 12 });
            document.Add(new Paragraph("Competition Level", subHeadingFont) { SpacingAfter = 6 });
            document.Add(new Paragraph(idea.CompetitionLevel ?? "Not assessed", bodyFont) { SpacingAfter = 12 });

            // ---- 6. Financial Projections ----
            if (idea.FinancialPlan != null)
            {
                document.NewPage();
                AddSectionHeader(document, "6. Financial Projections", headingFont);

                var finTable = new PdfPTable(2) { WidthPercentage = 100, SpacingBefore = 10 };
                finTable.SetWidths(new[] { 1f, 1f });
                AddTableRow(finTable, "Initial Investment", $"{idea.FinancialPlan.InitialInvestment:N0} JOD", boldFont, bodyFont);
                AddTableRow(finTable, "Monthly Revenue", $"{idea.FinancialPlan.MonthlyRevenue:N0} JOD", boldFont, bodyFont);
                AddTableRow(finTable, "Monthly Costs", $"{idea.FinancialPlan.MonthlyCosts:N0} JOD", boldFont, bodyFont);
                AddTableRow(finTable, "Monthly Profit", $"{(idea.FinancialPlan.MonthlyRevenue - idea.FinancialPlan.MonthlyCosts):N0} JOD", boldFont, bodyFont);
                AddTableRow(finTable, "Break-Even", idea.FinancialPlan.BreakEvenMonths > 0 ? $"{idea.FinancialPlan.BreakEvenMonths} months" : "N/A", boldFont, bodyFont);
                AddTableRow(finTable, "2-Year ROI", $"{idea.FinancialPlan.RoiPercentage:F1}%", boldFont, bodyFont);
                document.Add(finTable);
            }

            document.Close();
            return memoryStream.ToArray();
        }

        private void AddSectionHeader(Document doc, string title, Font font)
        {
            doc.Add(new Paragraph(title, font) { SpacingAfter = 15 });
            doc.Add(new Paragraph(new Chunk(new iTextSharp.text.pdf.draw.LineSeparator(1f, 100f, LightGray, Element.ALIGN_LEFT, -1))));
            doc.Add(new Paragraph("\n"));
        }

        private void AddTableRow(PdfPTable table, string label, string value, Font labelFont, Font valueFont)
        {
            var labelCell = new PdfPCell(new Phrase(label, labelFont)) { Padding = 8, BackgroundColor = LightGray, BorderColor = BaseColor.White };
            var valueCell = new PdfPCell(new Phrase(value, valueFont)) { Padding = 8, BorderColor = BaseColor.White };
            table.AddCell(labelCell);
            table.AddCell(valueCell);
        }

        private void AddSwotSection(Document doc, string title, JsonElement root, string key, BaseColor bgColor, Font headFont, Font bodyFont)
        {
            if (root.TryGetProperty(key, out var items) && items.ValueKind == JsonValueKind.Array)
            {
                var cell = new PdfPTable(1) { WidthPercentage = 100, SpacingBefore = 8 };
                var headerCell = new PdfPCell(new Phrase(title, headFont)) { BackgroundColor = bgColor, Padding = 10, BorderColor = BaseColor.White };
                cell.AddCell(headerCell);

                var list = new List(List.UNORDERED);
                list.SetListSymbol("\u2022  ");
                foreach (var item in items.EnumerateArray())
                {
                    list.Add(new ListItem(item.GetString() ?? "", bodyFont));
                }
                var contentCell = new PdfPCell { Padding = 10, BorderColor = BaseColor.White };
                contentCell.AddElement(list);
                cell.AddCell(contentCell);
                doc.Add(cell);
            }
        }

        private class PageNumberEvent : PdfPageEventHelper
        {
            public override void OnEndPage(PdfWriter writer, Document document)
            {
                var font = FontFactory.GetFont(FontFactory.HELVETICA, 8, new BaseColor(148, 163, 184));
                var table = new PdfPTable(1) { TotalWidth = document.PageSize.Width - 100 };
                var cell = new PdfPCell(new Phrase($"Page {writer.PageNumber} | Mashroo3i Business Plan", font))
                {
                    Border = Rectangle.NO_BORDER,
                    HorizontalAlignment = Element.ALIGN_CENTER
                };
                table.AddCell(cell);
                table.WriteSelectedRows(0, -1, 50, 40, writer.DirectContent);
            }
        }
    }
}
