// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260326072531_AddTypedFieldsToFinancialPlan")]
    partial class AddTypedFieldsToFinancialPlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.BusinessIdea", b =>
                {
                    b.Property<int>("IdeaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdeaId"));

                    b.Property<string>("AmmanRegion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("central");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("B2C");

                    b.Property<string>("BusinessTypeReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProblemStatement")
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("other");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Usp")
                        .HasColumnType("text");

                    b.HasKey("IdeaId");

                    b.HasIndex("UserId");

                    b.ToTable("BusinessIdeas");
                });

            modelBuilder.Entity("backend.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvaluationId"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdeaId")
                        .HasColumnType("integer");

                    b.Property<int>("MarketPotentialScore")
                        .HasColumnType("integer");

                    b.Property<int>("NoveltyScore")
                        .HasColumnType("integer");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendations")
                        .HasColumnType("text");

                    b.Property<string>("RedFlags")
                        .HasColumnType("text");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SwotAnalysis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Verdict")
                        .HasColumnType("text");

                    b.HasKey("EvaluationId");

                    b.HasIndex("IdeaId")
                        .IsUnique();

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("backend.Models.FinancialPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<decimal>("ARR")
                        .HasColumnType("numeric");

                    b.Property<int>("BreakEvenMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("BreakEvenUnits")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CAC")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinancialSummary")
                        .HasColumnType("text");

                    b.Property<decimal>("GrossMarginPct")
                        .HasColumnType("numeric");

                    b.Property<int>("IdeaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("InitialInvestment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LTV")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LtvCacRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyProfit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RoiPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PlanId");

                    b.HasIndex("IdeaId")
                        .IsUnique();

                    b.ToTable("FinancialPlans");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("BusinessInterest")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Experience")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backend.Models.BusinessIdea", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("BusinessIdeas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Evaluation", b =>
                {
                    b.HasOne("backend.Models.BusinessIdea", "BusinessIdea")
                        .WithOne("Evaluation")
                        .HasForeignKey("backend.Models.Evaluation", "IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessIdea");
                });

            modelBuilder.Entity("backend.Models.FinancialPlan", b =>
                {
                    b.HasOne("backend.Models.BusinessIdea", "BusinessIdea")
                        .WithOne("FinancialPlan")
                        .HasForeignKey("backend.Models.FinancialPlan", "IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessIdea");
                });

            modelBuilder.Entity("backend.Models.BusinessIdea", b =>
                {
                    b.Navigation("Evaluation");

                    b.Navigation("FinancialPlan");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("BusinessIdeas");
                });
#pragma warning restore 612, 618
        }
    }
}
